upload_dicom_sequence_http = "http://kt_service:5001/uploadDicomSequence/"
upload_dicom_sequence_custom_http = "http://kt_service:5001/uploadDicomSequenceCustom/"
upload_dicom_frame_http = "http://kt_service:5001/uploadDicomFrame/"
upload_image_axial_slice_http = "http://kt_service:5001/uploadImageAxialSlice/"
upload_nii_http = "http://kt_service:5001/uploadNII/"